code-share/config/routes.rb
CodeShare::Application.routes.draw do
  resources :links

  get "static_pages/links"
  resources :snippets, :path => '/'

  get '/codeedit', :to => redirect('/codeedit.html')

end

code-share/app/models/link.rb
class Link < ActiveRecord::Base
end

code-share/app/models/snippet.rb
class Snippet < ActiveRecord::Base
	validates :text, presence: true
end

code-share/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

code-share/app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: "secsec"

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :link)
    end
end

code-share/app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "secsec", only: :destroy

	def new
	end

	def create
		@snippet = Snippet.new(snippet_params)
 
		@snippet.save
		redirect_to @snippet
	end

	def show
  		@snippet = Snippet.find(params[:id])
	end

	def index
  		@snippets = Snippet.order(created_at: :desc)
  		@links = Link.all
	end

	def destroy
  		@snippet = Snippet.find(params[:id])
  		@snippet.destroy
 
  		redirect_to snippets_path
	end

	private
  		def snippet_params
    		params.require(:snippet).permit(:title, :author, :text)
  		end
end

code-share/app/helpers/application_helper.rb
module ApplicationHelper
end

code-share/app/helpers/links_helper.rb
module LinksHelper
end

code-share/app/helpers/snippets_helper.rb
module SnippetsHelper
end

code-share/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ru'>
<head>
  <title>Клуб программирования, г. Истра</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
</head>
<body>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

code-share/app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code-share/app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

code-share/app/views/links/index.html.erb
<h1>Ссылки</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Линк</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to link.title,link.link  %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

code-share/app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

code-share/app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @link.link %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

code-share/app/views/snippets/_new.html.erb
<h1>Новый сниппет</h1>
<%= form_for :snippet,  url: snippets_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :rows => 20%>
  </p>
 
  <p>
    <%= f.submit "Сохранить сниппет" %>
  </p>
<% end %>

code-share/app/views/snippets/index.html.erb
<div class="row">
  <div class="col-md-3"><%= render "new" %></div>
  <div class="col-md-5">   
    <h1>Совместный редактор кода</h1>
    <a href="/codeedit" class="btn btn-primary">Перейти к редактированию и просмотру кода</a>
    <h1>Сохраненные сниппеты</h1>    
    <table class="table table-striped">
      <tr>
        <th>Открыть </th>
        <th>Название </th>
        <th>Автор </th>
        <th>Создан</th>
      </tr>
     
      <% @snippets.each do |snippet| %>
        <tr>
          <td><%= link_to snippet.id, snippet_path(snippet), :class => "btn btn-primary" %></td>
          <td><%= snippet.title %></td>
          <td><%= snippet.author %></td>
          <td><%= snippet.updated_at %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="col-md-4">
    <h1>Полезные ссылки</h1>
    <%= @links.map{|link| link_to link.title, link.link, :class => "btn btn-primary"}.join('<br/>').html_safe  %>
    <!-- <a href="http://vk.com/programming_club_istra" class='btn btn-primary'>Группа ВКонтакте</a> -->
    <!-- <a href="https://github.com/Kulikovpavel/Programming-club" class='btn btn-primary'>Примеры использования</a> -->
  </div>
</div>

code-share/app/views/snippets/new.html.erb
<%= render "new" %>

code-share/app/views/snippets/show.html.erb
<div class="row">
  	<p><%= link_to "На главную страницу", snippets_path, :class => "btn btn-primary" %></p>
	<p>
	  <strong>ID:</strong>
	  <%= @snippet.id %>
	</p>

	<p>
	  <strong>Название:</strong>
	  <%= @snippet.title %>
	</p>

	<p>
	  <strong>Автор:</strong>
	  <%= @snippet.author %>
	</p>
	 
	<p>
	  <strong>Код:</strong>
	  <pre class="prettyprint linenums">
<%= @snippet.text %>
	  </pre>
	</p>

	<p class='text-right'>
	  <%= link_to "Удалить", snippet_path(@snippet), method: :delete, :class => "btn btn-warning btn-xs" %>
	</p>

</div>